group: bluezone
sudo: required
dist: trusty
before_install:
  - export TZ=Etc/UTC
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run test:ci-cypress
